FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /test-docker/test2

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore .\\test2\\test2.csproj
# Build and publish a release
RUN dotnet publish .\\test2\\test2.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /test-docker/test2
COPY --from=build-env /test-docker/test2/out .
ENTRYPOINT ["dotnet", "test2.dll"]