FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build-env
WORKDIR /test-docker/test1

# Copy everything
COPY . ./
# Restore as distinct layers
RUN dotnet restore .\\test1\\test1.csproj
# Build and publish a release
RUN dotnet publish .\\test1\\test1.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/aspnet:6.0
WORKDIR /test-docker/test1
COPY --from=build-env /test-docker/test1/out .
ENTRYPOINT ["dotnet", "test1.dll"]